name: Compile Thesis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest # Uses Ubuntu runner

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Nix
        run: |
          # Install Nix on Ubuntu-based systems
          curl -L https://nixos.org/nix/install | sh
          # Source the Nix profile for this shell session
          . $HOME/.nix-profile/etc/profile.d/nix.sh
          nix --version

      - name: Enable experimental features for Nix flakes
        run: |
          # Source the Nix profile and enable experimental features
          . $HOME/.nix-profile/etc/profile.d/nix.sh
          mkdir -p ~/.config/nix
          echo 'experimental-features = nix-command flakes' >> ~/.config/nix/nix.conf

      - name: Remove old PDF if exists
        run: |
          if [ -f output/Bachelorarbeit.pdf ]; then
            rm output/Bachelorarbeit.pdf
          fi

      - name: Enter nix develop environment and compile Thesis
        run: |
          # Source the Nix profile for the current shell session
          . $HOME/.nix-profile/etc/profile.d/nix.sh
          mkdir -p output
          cd projektarbeit
          nix develop --option filter-syscalls false
          typst compile thesis.typ ../output/bachelorarbeit.pdf

      - name: Upload PDF as artifact
        uses: actions/upload-artifact@v4
        with:
          name: Bachelorarbeit
          path: output/Bachelorarbeit.pdf
